### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by HeleneMk** [tfnjekeu/tfnjekeu.github.io#1]
Hey B. i was reading your documentation, and let me tell you i so proud of you, you made good job, your had interesting subject. Despite it was a big subject, you make essentiel. You will be a big data analyst and data scientist.
After read this issues , delete that.

**Comment by tfnjekeu** [comment]
It is okay B. Thank you for the support❤️. It is my personal repo. No obligation to delete or not.
